### PR TITLE
Add Article

### PR DESCRIPTION
**Pull request by nebillo**
This post demonstrates an approach for writing reusable UIViewControllers using Swift's Protocol Oriented Programming.

### CODE REVIEW

**Comment by mariusc** [comment]
Hey; I was wondering why I didn't get the PR on iOS Goodies. It looks like you actually opened a PR to your own fork of the repo. The base fork of the PR should be `iOS-Goodies/iOS-Goodies`. Let me know if you need help with it. Or if it seems too complicated, I can just add the article myself :). In general, we encourage PRs to iOS-Goodies.

**Comment by nebillo** [comment]
hey @mariusc thanks for letting me know. I can do it but I don't understand how can you help please? thanks

**Comment by mariusc** [comment]
GitHub tried to explain this workflow here https://help.github.com/articles/creating-a-pull-request-from-a-fork/. Let me know if it's still not clear :)

**Comment by nebillo** [comment]
done! https://github.com/iOS-Goodies/iOS-Goodies/pull/964
thanks again :)

**Pull request merged**
